# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# a list of available adjectives
Adjective.delete_all
Adjective.create(name: "綺麗だ", antonym: "醜い", eng_name: "beautiful")
Adjective.create(name: "楽しい", antonym: "つまらない", eng_name: "entertaining")
Adjective.create(name: "快適だ", antonym: "不快だ", eng_name: "comfortable")
Adjective.create(name: "快適だ", antonym: "不快だ", eng_name: "friendly")
Adjective.create(name: "心地よい", antonym: "不快だ", eng_name: "soothing")
Adjective.create(name: "賢い", antonym: "バカだ", eng_name: "clever")
Adjective.create(name: "かっこいい", antonym: "", eng_name: "cool")
Adjective.create(name: "かわいい", antonym: "", eng_name: "lovely")
Adjective.create(name: "かわいい", antonym: "", eng_name: "cute")
Adjective.create(name: "おいしい", antonym: "まずい", eng_name: "delicious")
Adjective.create(name: "甘い", antonym: "", eng_name: "sweet")
Adjective.create(name: "酸っぱい", antonym: "", eng_name: "sour")
Adjective.create(name: "苦い", antonym: "", eng_name: "bitter")
Adjective.create(name: "辛い", antonym: "", eng_name: "spicy")
Adjective.create(name: "好きだ", antonym: "嫌いだ", eng_name: "preferable")
Adjective.create(name: "好きだ", antonym: "嫌いだ", eng_name: "likable")
Adjective.create(name: "嫌いだ", antonym: "好きだ", eng_name: "unpleasant")
Adjective.create(name: "安全だ", antonym: "危険だ", eng_name: "safe")
Adjective.create(name: "有名だ", antonym: "無名だ", eng_name: "famous")
Adjective.create(name: "面白い", antonym: "つまらない", eng_name: "amusing")
Adjective.create(name: "怖い", antonym: "", eng_name: "fearful")
Adjective.create(name: "興味深い", antonym: "", eng_name: "exciting")
Adjective.create(name: "好調だ", antonym: "不調だ", eng_name: "healthy")
Adjective.create(name: "幸せだ", antonym: "不幸だ", eng_name: "happy")
Adjective.create(name: "おしゃれだ", antonym: "ダサい", eng_name: "fashonable")
Adjective.create(name: "簡単だ", antonym: "難しい", eng_name: "easy")
Adjective.create(name: "安い", antonym: "高い", eng_name: "cheap")
Adjective.create(name: "近い", antonym: "遠い", eng_name: "near")
Adjective.create(name: "強い", antonym: "弱い", eng_name: "strong")
Adjective.create(name: "速い", antonym: "遅い", eng_name: "fast")
Adjective.create(name: "早い", antonym: "遅い", eng_name: "early")
Adjective.create(name: "大きい", antonym: "小さい", eng_name: "large")
Adjective.create(name: "長い", antonym: "短い", eng_name: "long")
Adjective.create(name: "広い", antonym: "狭い", eng_name: "broad")
Adjective.create(name: "浅い", antonym: "", eng_name: "shallow")
Adjective.create(name: "低い", antonym: "高い", eng_name: "low")
Adjective.create(name: "重い", antonym: "軽い", eng_name: "heavy")
Adjective.create(name: "新しい", antonym: "古い", eng_name: "new")
Adjective.create(name: "若い", antonym: "", eng_name: "young")
Adjective.create(name: "温暖だ", antonym: "寒冷だ", eng_name: "warm")
Adjective.create(name: "暑い", antonym: "寒い", eng_name: "hot")
Adjective.create(name: "古い", antonym: "新しい", eng_name: "old")
Adjective.create(name: "多い", antonym: "少ない", eng_name: "numerous")
Adjective.create(name: "忙しい", antonym: "暇だ", eng_name: "busy")
Adjective.create(name: "裕福だ", antonym: "", eng_name: "rich")
Adjective.create(name: "上品だ", antonym: "下品だ", eng_name: "elegant")
Adjective.create(name: "悲惨だ", antonym: "", eng_name: "miserable")
Adjective.create(name: "平和だ", antonym: "", eng_name: "peaceful")
Adjective.create(name: "便利だ", antonym: "不便だ", eng_name: "useful")
Adjective.create(name: "奥深い", antonym: "", eng_name: "profound")
Adjective.create(name: "クリーンだ", antonym: "", eng_name: "clean")
Adjective.create(name: "ヘルシーだ", antonym: "", eng_name: "salubrious")
